# [[main]]
#   name = "About"
#   pageRef = "/about/"
#   weight = 10

# [[main]]
#   name = "Blog"
#   pageRef = "/blog/"
#   weight = 20

# [[main]]
#   name = "Projects"
#   pageRef = "/projects/"
#   weight = 30

# [[main]]
#   name = "Sample project"
#   pageRef = "/projects/sample-project/"
#   parent = "Projects"
#   weight = 1

# [[main]]
#   name = "Another project"
#   pageRef = "/projects/another-project/"
#   parent = "Projects"
#   weight = 2

# [[main]]
#   name = "Tags"
#   pageRef = "/tags/"
#   weight = 40

[[social]]
  name = "Zhihu"
  pre = "fab Zhihu"
  url = "https://www.zhihu.com/people/roseduan"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/roseduan"
  weight = 20

[[social]]
  name = "Weixin"
  pre = "fab weixin"
  url = "https://mp.weixin.qq.com/s/hs36eiU7Zr-UdJ0YBtZgKQ"
  weight = 30

# [[sample]]
#   name = "Blog"
#   pageRef = "/blog/"
#   weight = 10

# [[sample]]
#   name = "Projects"
#   pageRef = "/projects/"
#   weight = 20

# [[sample]]
#   name = "Sample project"
#   pageRef = "/projects/sample-project/"
#   parent = "Projects"
#   weight = 1

# [[sample]]
#   name = "Another project"
#   pageRef = "/projects/another-project/"
#   parent = "Projects"
#   weight = 2
